# Hyas (gethyas)

## Feed
copyRight = "Copyright (c) 2020-2021 Henk Verlinde"

# SEO (@hyas/seo)

## Homepage
title = "Doks"
titleSeparator = "-" # - (default)
titleAddition = "Modern Documentation Theme"
description = "Doks is a Hyas theme for building custom, production-ready documentation websites." # Default description

## Open Graph
images = ["hyas.png"]
ogLocale = "en_US"
titleHome = "Modern Documentation Theme"

## Twitter Cards
twitterSite = "@gethyas"
twitterCreator = "@henkverlinde"

## JSON-LD
schemaType = "Organization" # Organization (default) or Person
schemaName = "Hyas"
schemaAuthor = "Henk Verlinde"
schemaAuthorTwitter = "https://twitter.com/henkverlinde"
schemaAuthorLinkedIn = "https://www.linkedin.com/in/henkverlinde/"
schemaAuthorGitHub = "https://github.com/h-enk"
schemaLocale = "en-US"
schemaLogo = "logo-hyas.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "hyas.png"
schemaImageWidth = 1280
schemaImageHeight = 640
schemaTwitter = "https://twitter.com/gethyas"
schemaLinkedIn = ""
schemaGitHub = "https://github.com/h-enk/hyas"

# Images (@hyas/images)

[lazyimg]
  resizer = "auto"
  renderer = "lqip-webp" # "lqip (default)"

  # Resizer options:
  lqipSize = "120x Gaussian"
  maxSize = "1024x" # "1920x" (default)
  responsiveSizes = [ "320x", "640x", "768x", "1024x", "1366x", "1600x", "1920x" ]
  resizeOptions = "Lanczos q95"

  # Renderer options:
  class = "img-fluid"
  # alt = "" # Default alt tag
  noscript = true

  errorHandler = "warning" # "warning-remote" (default)
